### ISSUE TITLE
Get HSC data inputs and determine what processing is needed

### ISSUE THREAD

**Issue by mdschneider** [LSSTDESC/WLMassMap#1]
The HSC survey team will release images in late February 2017. We need to determine what formats are available and what processing we'll need to apply to these images to make them ready for our shape measurements.

It's also possible that images reprocessed by the LSST DM team in 2017 could be useful for these project. We need to evaluate what formats may be available on what timeline and whether the DM processing is more viable for our project than the raw data release from HSC.

Also, we might start getting our pipeline running using the HSC images of dense stellar fields that @joezuntz has been processing with DM in 2016.

**Comment by EiffL** [comment]
outdated
